


let product = [
  {
    id: 1,
    name: "Iphone 14 Pro Max 8/512gb",
    brend: "Apple",
    img: "./images/apple-iphone-14-pro-makh.jpeg",
    narxi: 1450,
    isActive: true,
  },
  {
    id: 2,
    name: "Iphone 12 Pro 6/256gb",
    brend: "Apple",
    img: "./images/apple-iphone-14-pro.jpeg",
    narxi: 829,
    isActive: false,
  },

  {
    id: 3,
    name: "Iphone 13 Pro Max 6/256gb",
    brend: "Apple",
    img: "./images/apple-iphone-13-pro-max.jpeg",
    narxi: 1299,
    isActive: true,
  },
  {
    id: 4,
    name: "Iphone 14 Pro 6/256gb",
    brend: "Apple",
    img: "./images/apple-iphone-14-pro.jpeg",
    narxi: 1350,
    isActive: true,
  },
  {
    id: 5,
    name: "Green Lion Ultra ",
    brend: "Green",
    img: "./images/green-lion-ultra.jpeg",
    narxi: 49,
    isActive: false,
  },
  {
    id: 6,
    name: "Hoco Y11 ",
    brend: "Hoco",
    img: "./images/Hoco-Y11.jpeg",
    narxi: 110,
    isActive: true,
  },
  {
    id: 7,
    name: "Huawe Nova 10 Pro 4/128gb",
    brend: "Huawe",
    img: "./images/huawe-nova-10-pro.jpeg",
    narxi: 899,
    isActive: true,
  },
  {
    id: 8,
    name: "Infinix smart 6 4/64gb",
    brend: "Infinix",
    img: "./images/infinix-smart-6.jpeg",
    narxi: 220,
    isActive: true,
  },
  {
    id: 9,
    name: "Nothing Phone 1 6/128gb",
    brend: "Nothing",
    img: "./images/nothing-phone-1.jpeg",
    narxi: 799,
    isActive: true,
  },
  {
    id: 10,
    name: "Novey X50",
    brend: "Novey",
    img: "./images/novey-X50.jpeg",
    narxi: 59,
    isActive: true,
  },
  {
    id: 12,
    name: "Oppo A17 4/64gb",
    brend: "Oppo",
    img: "./images/Oppo-A17.jpeg",
    narxi: 339,
    isActive: false,
  },
  {
    id: 12,
    name: "Redmi Note 11 6/128gb",
    brend: "Xiaomi",
    img: "./images/redmi_note-11.jpeg",
    narxi: 599,
    isActive: true,
  },
  {
    id: 13,
    name: "Samsung Galaxy S23 Ultra",
    brend: "Samsung",
    img: "./images/S23_ultra.jpeg",
    narxi: 1599,
    isActive: true,
  },
  {
    id: 14,
    name: "Samsung Galaxy S23+",
    brend: "Samsung",
    img: "./images/samsung-S23.jpeg",
    narxi: 1499,
    isActive: true,
  },
  {
    id: 15,
    name: "Samsung Galaxy Z Flip4",
    brend: "Samsung",
    img: "./images/samsung-galaxy-z-flip4.jpeg",
    narxi: 999,
    isActive: true,
  },
  {
    id: 16,
    name: "Tecno Camon 19 Pro",
    brend: "Tecno",
    img: "./images/tecno-camon-19-pro.jpeg",
    narxi: 399,
    isActive: true,
  },
  {
    id: 17,
    name: "Vivo V25-5g 4/128gb",
    brend: "Vivo",
    img: "./images/vivo-v25-5g.jpeg",
    narxi: 229,
    isActive: false,
  },
  {
    id: 18,
    name: "Wonlex KT27 Pro",
    brend: "Wonlex",
    img: "./images/Wonlex-KT27.jpeg",
    narxi: 119,
    isActive: true,
  },
  {
    id: 19,
    name: "Xiaomi Amazfit T Rex Pro",
    brend: "Xiaomi",
    img: "./images/Xiaomi-Amazfit_T-Rex-Pro.jpeg",
    narxi: 129,
    isActive: false,
  },
  {
    id: 20,
    name: "Xiaomi Redmi Note 11se",
    brend: "Xiaomi",
    img: "./images/xiaomi-redmi-note-11se.jpeg",
    narxi: 699,
    isActive: true,
  },
  {
    id: 21,
    name: "Honor X9 6/128gb",
    brend: "Honor",
    img: "./images/honor-x9.jpeg",
    narxi: 699,
    isActive: true,
  },
];